def update_dart(new_version)
  path = Dir['../**/qonversion.dart'].first
  regex = /static const String _sdkVersion = ".*";/
  result_value = "static const String _sdkVersion = \"#{new_version}\";"

  update_file(path, regex, result_value)
end

def update_yaml(new_version)
  path = "../pubspec.yaml"
  regex = /version: .*/
  result_value = "version: #{new_version}"

  update_file(path, regex, result_value)
end

def update_file(path, regex, result_value)
  file = File.read(path)
  new_content = file.gsub(regex, result_value)
  File.open(path, 'w') { |line| line.puts new_content }
end

def update_changelog(new_version)
  path = "../CHANGELOG.md"
  file = File.read(path)
  File.open(path, 'w') { |line| line.puts "\#\# #{new_version}\n* // Update changelog here\n\n" + file }


  # path = "../CHANGELOG.md"
  # # file = File.read(path)
  # file = File.open(path, 'r+')
  # file.write "\#\# #{new_version}\n* // Update changelog here\n\n"
end

lane :bump do |options|
  new_version = options[:version]

  update_dart(new_version)
  update_yaml(new_version)
  update_changelog(new_version)
end
