name: Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Validation
        run: |
          flutter pub publish --dry-run
